version: "3.8"
services:
    db:
        image: postgres
        container_name: pgdb_container
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        volumes:
            - local_pgdata:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_pgdb_container
        restart: always
        ports:
            - "8888:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: kaziashik999@gmail.com
            PGADMIN_DEFAULT_PASSWORD: root
        volumes:
            - pgadmin-data:/var/lib/pgadmin

volumes:
    local_pgdata:
    pgadmin-data:
